config/routes.rb
Rails.application.routes.draw do
  get 'home/display_all' ,to: "home#display_all"
  get 'uploads/index'
  devise_for :users
  root "home#index"

  resources :users do
    resources :uploads
  end
  
  resources :uploads do
    resources :comments 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :upload
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :photo
  # class_methods do
  #   def upload_count
  #     # uploads.where(user.id=current_user)count
  #     (current_user).uploads.count
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :uploads, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :avatar) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password, :avatar)
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true
# 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
class CommentsController < ApplicationController
  before_action :set_upload, only: %i[create destroy]
  before_action :set_comment, only: :destroy

  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = upload_comments.create(comment_params)

    redirect_to upload_path(@upload) if @comment.save
  end

  def destroy
    @comment.destroy

    redirect_to upload_path(@upload), status: :see_other
  end

  private

  def set_upload
    @upload = Upload.find(params[:upload_id])
  end

  def set_comment
    @comment = upload_comments.find(params[:id])
  end

  def upload_comments
    @upload.comments
  end

  def comment_params
    params.require(:comment).permit!
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    if !current_user == nil?
      @uploads = Upload.all.paginate(page: params[:page], per_page: 4)
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/uploads_controller.rb
# frozen_string_literal: true

class UploadsController < ApplicationController
  def index
    @uploads = current_user.uploads.paginate(page: params[:page], per_page: 4)
  end

  def new
    @upload = Upload.new
  end

  def show
    @upload = Upload.find(params[:id])
  end

  def create
    @user = User.find_by(id: current_user.id)
    @upload = @user.uploads.create(upload_params)
    if @upload.save
      redirect_to user_uploads_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @upload = Upload.find(params[:id])
  end

  def update
    @upload = Upload.find(params[:id])

    if @upload.update(upload_params)
      redirect_to upload_path(@upload)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy
    redirect_to user_uploads_path(@upload)
  end

  private

  def upload_params
    params.require(:upload).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.commenter %> :</strong>
  <%= comment.body %>
</p>



<p>
  <%= button_to "Delete", [comment.upload , comment], class:"btn btn-primary", method: :delete, data:{
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
  }%>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @upload, @upload.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter, class:"form-control"%>
  </p>
  
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, class:"form-control" %>
  </p>
  <p>
    <%= form.submit class:"btn btn-success"%>
  </p>
<% end %>

app/views/home/display.html.erb
<h1>Clonogram</h1>
<% @uploads.each do |upload| %>
<%= upload.photo%><br>
<%end%>

app/views/home/index.html.erb
<div class="container">
  <h1 class="text-center">Clonogram</h1>
  <div class="row">
    <% @uploads.each do |upload| %>
    <div class="col-3 my-3">
      <div class="card" style="width: 18rem;">
        <div class="card"></div>
        <div class="card-header"><%=image_tag upload.user.avatar, width:"15%"%><%=upload.uploaded_by%></div>
        <%=image_tag upload.photo, class:"upload-image" %>
        <div class="card-body">
          <h5 class="card-title"> </h5>
          <p class="d-inline-flex gap-1">
          <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
          DETAILS  </a>
          </p>

          <div class="collapse" id="collapseExample">
            <div class="card card-body">
            <%= upload.info %>
        </div>
        </div>
        </div>
      </div>
    </div>
  <%end%>
  
  <div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @uploads %>
  </div>
  <%= will_paginate @uploads, :container => false %>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href= <%= root_path %> >HOME</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    

   
    <% if user_signed_in? %> 
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=<%=uploads_index_path%>>MY POSTS</a>
          </li>
          <li>
            <%= link_to "UPLOAD POST", new_upload_path, class:"nav-link"%>
          </li>
        </ul>
      

        <ul>
          <%= button_to "Light-Mode", "#", class:"btn btn-primary action-button mx-2 my-1" %>
          <%= button_to "Dark- Mode", "#", class:"btn btn-primary action-button mx-2" %>
        </ul>
        <div class="me-2">
        Welcome :- <%= current_user.email %> 
        </div>
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, class:"user-avatar" %>
        <% end %>     

        <%= link_to 'Edit Profile ', edit_user_registration_path,class:"btn btn-primary text-center ms-3   me-3" %>

        <%= button_to "Sign out", destroy_user_session_path, class: "btn btn-primary", method: :delete %> 

    <% else %>
      <div>
        <%= button_to "Sign in", new_user_session_path, class: "btn btn-primary sign_in_button" %>
      </div> 
    <% end %>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <header style=text-align:center>Clonogram</header>
    <%= render "layouts/navbar" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/uploads/_form.html.erb
<%= form_with model: upload do |form| %>
  <div>
    <%= form.label :photo%><br>
    <%= form.file_field :photo ,class:"form-control" %>
    
  </div>

  <div>
    <%= form.label :info %><br>
    <%= form.text_area :info ,class:"form-control"%><br>
    
  </div>

    <div>
    <%= form.hidden_field :uploaded_by, value: current_user.name %><br>
  </div>

  <div>
    <%= form.submit class:"btn btn-success"%>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Edit Post</h1>
<%= render "form", upload:@upload %>

app/views/uploads/index.html.erb
<div class="container">
<h1 style="text-align:center">My Uploads</h1>
  <div class="row">
    <% @uploads.each do |upload| %>
    <div class="col-3 my-3">
      <div class="card" style="width: 18rem ">
        <div card-header=<%=upload.uploaded_by%>></div>
        <%=image_tag upload.photo, class:"user-uploads" %>
        <div class="card-body">
          <h5 class="card-title"></h5>
          <div class="container">
            <p class="card-text">
                <a class="btn btn-primary " data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample"> DETAILS  </a>
              
              <div class="collapse" id="collapseExample">
                <div class="card card-body"> <%= upload.info %> </div>
            </p>
          </div>
        </div>
        <%= button_to "SHOW", upload_path(upload), class: "btn btn-primary", method: :get %>
      </div>
    </div>
  </div>
<% end %>


  <div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @uploads %>
    </div>
    <%= will_paginate @uploads, :container => false %>
  </div>
</div>

app/views/uploads/new.html.erb
<div class="container">
  <h1>New Post</h1>
  <%= render "form", upload:@upload %>
</div>

app/views/uploads/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4"><%=image_tag @upload.photo, class:"user-uploads" %></div>
    <div class="col-sm-8 word-wrap ">
        <%= @upload.info %>
    </div>
  </div>
</div>

</div>
  </div>


  <div class="container">
    <%if(@upload.user_id == current_user.id)%>
        <div style="text-align:center">
            <%= button_to "EDIT",edit_upload_path, class: "btn btn-primary ", method: :get%><br>
            <%= button_to "DESTROY", upload_path(@upload), class: "btn btn-primary", method: :delete, data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
            } %>
    <%end%>
   </div>
  </div>

</div>

<hr>

<div class="container">
<h1><u>COMMENTS</u></h1>
    <%= render @upload.comments %>

    <h2>ADD COMMENTS </h2>
    <%= render 'comments/form' %>
</div>